#ifndef DHCP_H_INCLUDED
#define DHCP_H_INCLUDED

/* https://www.rfc-editor.org/rfc/rfc2131
 * https://www.rfc-editor.org/rfc/rfc1533
 */

#include <stdint.h>
#include <stddef.h>

#define DHCP_OPT_MAXLEN 256

typedef struct __attribute__((packed)) dhcp_msg {
  uint8_t op;
  uint8_t htype;
  uint8_t hlen;
  uint8_t hops;
  uint32_t xid;
  uint16_t secs;
  uint16_t flags;
  uint32_t ciaddr;
  uint32_t yiaddr;
  uint32_t siaddr;
  uint32_t giaddr;
  uint8_t chaddr[16];
  uint8_t sname[64];
  uint8_t file[128];
  uint8_t options[312];
} dhcp_msg_t;

typedef struct dhcp_opt {
  uint8_t buf[DHCP_OPT_MAXLEN];
  uint8_t len;
  uint8_t tag;
} dhcp_opt_t;

typedef struct dhcp_opt_iterator {
  uint8_t *opts;
  size_t left;
  int done;
} dhcp_opt_iterator_t;

dhcp_opt_iterator_t dhcp_opt_iterator_init (dhcp_msg_t *msg);
int dhcp_opt_add_magic_cookie (dhcp_opt_iterator_t *it);
int dhcp_opt_take_magic_cookie (dhcp_opt_iterator_t *it);
int dhcp_opt_add_option (const dhcp_opt_t *opt, dhcp_opt_iterator_t *it);
int dhcp_opt_take_option (dhcp_opt_t *opt, dhcp_opt_iterator_t *it);

const char *dhcp_msg_type_str (uint8_t type);
const char *dhcp_opt_str (uint8_t opt);

enum dhc_msg_type {
  DHCP_MSG_TYPE_DHCPDISCOVER = 1,
  DHCP_MSG_TYPE_DHCPOFFER = 2,
  DHCP_MSG_TYPE_DHCPREQUEST = 3,
  DHCP_MSG_TYPE_DHCPDECLINE = 4,
  DHCP_MSG_TYPE_DHCPACK = 5,
  DHCP_MSG_TYPE_DHCPNAK = 6,
  DHCP_MSG_TYPE_DHCPRELEASE = 7,
};

enum dhc_port {
  DHCP_PORT_SERVER = 67,
  DHCP_PORT_CLIENT = 68,
};

enum dhcp_flag {
  DHCP_FLAG_UNICAST = 0x0000,
  DHCP_FLAG_BROADCAST = 0x8000,
};

enum dhcp_op {
  DHCP_OP_BOOTREQUEST = 1,
  DHCP_OP_BOOTREPLY = 2,
};

enum dhcp_opt_tag {
  DHCP_OPT_PAD_OPTION = 0,
  DHCP_OPT_SUBNET_MASK = 1,
  DHCP_OPT_TIME_OFFSET = 2,
  DHCP_OPT_ROUTER_OPTION = 3,
  DHCP_OPT_TIME_SERVER_OPTION = 4,
  DHCP_OPT_NAME_SERVER_OPTION = 5,
  DHCP_OPT_DOMAIN_NAME_SERVER_OPTION = 6,
  DHCP_OPT_LOG_SERVER_OPTION = 7,
  DHCP_OPT_COOKIE_SERVER_OPTION = 8,
  DHCP_OPT_LPR_SERVER_OPTION = 9,
  DHCP_OPT_IMPRESS_SERVER_OPTION = 10,
  DHCP_OPT_RESOURCE_LOCATION_SERVER_OPTION = 11,
  DHCP_OPT_HOST_NAME_OPTION = 12,
  DHCP_OPT_BOOT_FILE_SIZE_OPTION = 13,
  DHCP_OPT_MERIT_DUMP_FILE = 14,
  DHCP_OPT_DOMAIN_NAME = 15,
  DHCP_OPT_SWAP_SERVER = 16,
  DHCP_OPT_ROOT_PATH = 17,
  DHCP_OPT_EXTENSIONS_PATH = 18,
  DHCP_OPT_IP_FORWARDING_ENABLE_DISABLE_OPTION = 19,
  DHCP_OPT_NON_LOCAL_SOURCE_ROUTING_ENABLE_DISABLE_OPTION = 20,
  DHCP_OPT_POLICY_FILTER_OPTION = 21,
  DHCP_OPT_MAXIMUM_DATAGRAM_REASSEMBLY_SIZE = 22,
  DHCP_OPT_DEFAULT_IP_TIME_TO_LIVE = 23,
  DHCP_OPT_PATH_MTU_AGING_TIMEOUT_OPTION = 24,
  DHCP_OPT_PATH_MTU_PLATEAU_TABLE_OPTION = 25,
  DHCP_OPT_INTERFACE_MTU_OPTION = 26,
  DHCP_OPT_ALL_SUBNETS_ARE_LOCAL_OPTION = 27,
  DHCP_OPT_BROADCAST_ADDRESS_OPTION = 28,
  DHCP_OPT_PERFORM_MASK_DISCOVERY_OPTION = 29,
  DHCP_OPT_MASK_SUPPLIER_OPTION = 30,
  DHCP_OPT_PERFORM_ROUTER_DISCOVERY_OPTION = 31,
  DHCP_OPT_ROUTER_SOLICITATION_ADDRESS_OPTION = 32,
  DHCP_OPT_STATIC_ROUTE_OPTION = 33,
  DHCP_OPT_TRAILER_ENCAPSULATION_OPTION = 34,
  DHCP_OPT_ARP_CACHE_TIMEOUT_OPTION = 35,
  DHCP_OPT_ETHERNET_ENCAPSULATION_OPTION = 36,
  DHCP_OPT_TCP_DEFAULT_TTL_OPTION = 37,
  DHCP_OPT_TCP_KEEPALIVE_INTERVAL_OPTION = 38,
  DHCP_OPT_TCP_KEEPALIVE_GARBAGE_OPTION = 39,
  DHCP_OPT_NETWORK_INFORMATION_SERVICE_DOMAIN_OPTION = 40,
  DHCP_OPT_NETWORK_INFORMATION_SERVERS_OPTION = 41,
  DHCP_OPT_VENDOR_SPECIFIC_INFORMATION = 42,
  DHCP_OPT_NETWORK_TIME_PROTOCOL_SERVERS_OPTION = 43,
  DHCP_OPT_NETBIOS_OVER_TCP_IP_NAME_SERVER_OPTION = 44,
  DHCP_OPT_NETBIOS_OVER_TCP_IP_DATAGRAM_DISTRIBUTION_SERVER_OPTION = 45,
  DHCP_OPT_NETBIOS_OVER_TCP_IP_NODE_TYPE_OPTION = 46,
  DHCP_OPT_NETBIOS_OVER_TCP_IP_SCOPE_OPTION = 47,
  DHCP_OPT_X_WINDOW_SYSTEM_FONT_SERVER_OPTION = 48,
  DHCP_OPT_X_WINDOW_SYSTEM_DISPLAY_MANAGER_OPTION = 49,
  DHCP_OPT_REQUESTED_IP_ADDRESS = 50,
  DHCP_OPT_IP_ADDRESS_LEASE_TIME = 51,
  DHCP_OPT_OPTION_OVERLOAD = 52,
  DHCP_OPT_DHCP_MESSAGE_TYPE = 53,
  DHCP_OPT_SERVER_IDENTIFIER = 54,
  DHCP_OPT_PARAMETER_REQUEST_LIST = 55,
  DHCP_OPT_MESSAGE = 56,
  DHCP_OPT_MAXIMUM_DHCP_MESSAGE_SIZE = 57,
  DHCP_OPT_RENEWAL = 58,
  DHCP_OPT_REBINDING = 59,
  DHCP_OPT_CLASS_IDENTIFIER = 60,
  DHCP_OPT_CLIENT_IDENTIFIER = 61,
  DHCP_OPT_END_OPTION = 255,
};

#endif
